### ISSUE TITLE
Rewrite IBM Backend

### ISSUE THREAD

**Issue by ausbin** [ORNL-QCI/xacc#7]
I've been reading through [the current IBM API documentation][1], and it seems very different compared to the current `IBMAccelerator` in XACC. Thankfully the new API appears to be simpler (for example, you send an OpenQASM 3 string, not a JSON "QObject"), but I think the IBMAccelerator needs a rewrite.

Please correct me if I'm wrong about this (it would be great if so)

[1]: https://docs.quantum.ibm.com/api/runtime

**Comment by danclaudino** [comment]
Thanks for posting this issue. This plugin needs a lot of work.

**Comment by danclaudino** [comment]
I forgot to reference it in the PR, but see #54. Everything still needs to be wrapped up in a normal JSON string, not a `QObject`, which can be populated with OpenQASM 2 and 3. It still needs more work, but the basic stuff can already be done.
